/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DtoWorkspaceData } from "./dtoworkspacedata";
import { Expose, Type } from "class-transformer";

export class DtoUpdateWorkspaceResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => DtoWorkspaceData)
    data?: DtoWorkspaceData;

    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "success" })
    success?: boolean;
}
