/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WorkspaceWorkspace } from "./workspaceworkspace";
import { Expose, Type } from "class-transformer";

export class DtoWorkspaceData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "workspace" })
    @Type(() => WorkspaceWorkspace)
    workspace?: WorkspaceWorkspace;
}
