/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class WorkspaceWorkspace extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "ID" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "createdAt" })
    createdAt?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "deletedAt" })
    deletedAt?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "ownerID" })
    ownerID?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "updatedAt" })
    updatedAt?: number;
}
